import { Person } from './TS';

export const data: Person[] = [
  {
    id: '12345',
    date: '10/02/2023',
    branch: 'Andheri',
    type: 'full',
    amount: '5,45,456',
    bank: 'HDFC',
    requested: 'Vikas Mehra',
  },
  {
    id: '67890',
    date: '13/05/2023',
    branch: 'Vira',
    type: 'Short',
    amount: '7,45,456',
    bank: 'SBI',
    requested: 'Admin User',
  },
  {
    id: '34567',
    date: '19/04/2023',
    branch: 'Andheri',
    type: 'full',
    amount: '3,45,456',
    bank: 'Axis',
    requested: 'Virat Kholi',
  },
  {
    id: '98765',
    date: '23/04/2023',
    branch: 'Thane',
    type: 'full',
    amount: '5,00,456',
    bank: 'Kotak',
    requested: 'Rishabh Pant',
  },
  {
    id: '12567',
    date: '17/04/2023',
    branch: 'Mumbai',
    type: 'Short',
    amount: '2,45,679',
    bank: 'ICCI',
    requested: 'Pankaj Singh',
  },
  {
    id: '67245',
    date: '29/06/2023',
    branch: 'New Mumbai',
    type: 'full',
    amount: '2,45,456',
    bank: 'SBI',
    requested: 'Test User',
  },
  {
    id: '90875',
    date: '19/04/2023',
    branch: 'Goregaon',
    type: 'full',
    amount: '5,45,456',
    bank: 'HDFC',
    requested: 'Rohit sharma',
  },
  {
    id: '32098',
    date: '19/04/2023',
    branch: 'Surat',
    type: 'full',
    amount: '59,45,456',
    bank: 'Kotak',
    requested: 'Ajinkya Rahane',
  },
];


export const states = [
  'Thane',
  'New Mumbai',
  'Mumbai',
  'Kurla',
  'Andheri',
  'Byculla',
  'Vile Parle',
  'Virar',
  'Surat',
  'Goregaon',
];
